// Parents
export const FETCH_PARENTS_SUCCESS = 'FETCH_PARENTS_SUCCESS';
export const FETCH_PARENTS_REQUEST = 'FETCH_PARENTS_REQUEST';
export const FETCH_PARENTS_ERROR = 'FETCH_PARENTS_ERROR';
export const ADD_PARENTS_SUCCESS = 'ADD_PARENTS_SUCCESS';
export const ADD_PARENTS_INFO = 'ADD_PARENTS_INFO';
export const TOGGLE_INITIAL_SEARCH = 'TOGGLE_INITIAL_SEARCH'; 

// Sitters
export const FETCH_SITTERS_REQUEST = 'FETCH_SITTERS_REQUEST';
export const FETCH_SITTERS_SUCCESS = 'FETCH_SITTERS_SUCCESS';
export const FETCH_SITTERS_ERROR = 'FETCH_SITTERS_ERROR';
export const SEARCH_SITTERS_SUCCESS = 'SEARCH_SITTERS_SUCCESS';
export const SEARCH_SITTERS_BY_ZIP_SUCCESS = 'SEARCH_SITTERS_BY_ZIP_SUCCESS'; 

// Views
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const TOGGLE_VIEW = 'TOGGLE_VIEW';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// Misc: Auth
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';