// Parents
export const FETCH_PARENTS_SUCCESS = 'FETCH_PARENTS_SUCCESS';
export const FETCH_PARENTS_REQUEST = 'FETCH_PARENTS_REQUEST';
export const FETCH_PARENTS_ERROR = 'FETCH_PARENTS_ERROR';
export const ADD_PARENTS_SUCCESS = 'ADD_PARENTS_SUCCESS';
export const ADD_PARENTS_INFO = 'ADD_PARENTS_INFO';

// Views
export const TOGGLE_FORM = 'TOGGLE_FORM';