// Parents
export const FETCH_PARENTS_SUCCESS = "FETCH_PARENTS_SUCCESS";
export const FETCH_PARENTS_REQUEST = "FETCH_PARENTS_REQUEST";
export const FETCH_PARENTS_ERROR = "FETCH_PARENTS_ERROR";
export const SEARCH_PARENTS_BY_ZIP_SUCCESS = "SEARCH_PARENTS_BY_ZIP_SUCCESS";
export const ADD_PARENTS_SUCCESS = "ADD_PARENTS_SUCCESS";
export const ADD_PARENTS_INFO_REQUEST = "ADD_PARENTS_INFO_REQUEST";
export const ADD_PARENTS_INFO_SUCCESS = "ADD_PARENTS_INFO_SUCCESS";
export const ADD_PARENTS_INFO_ERROR = "ADD_PARENTS_INFO_ERROR";
export const TOGGLE_INITIAL_SEARCH = "TOGGLE_INITIAL_SEARCH";

export const FETCH_BIO_REQUEST = "FETCH_BIO_REQUEST";
export const FETCH_BIO_SUCCESS = "FETCH_BIO_SUCCESS";
export const FETCH_BIO_ERROR = "FETCH_BIO_ERROR";

// Sitters
export const FETCH_SITTERS_REQUEST = "FETCH_SITTERS_REQUEST";
export const FETCH_SITTERS_SUCCESS = "FETCH_SITTERS_SUCCESS";
export const FETCH_SITTERS_ERROR = "FETCH_SITTERS_ERROR";
export const SEARCH_SITTERS_SUCCESS = "SEARCH_SITTERS_SUCCESS";
export const SEARCH_SITTERS_BY_ZIP_SUCCESS = "SEARCH_SITTERS_BY_ZIP_SUCCESS";
export const ADD_SITTER_BIO_SUCCESS = "ADD_SITTER_BIO_SUCCESS";

// Views
export const TOGGLE_FORM = "TOGGLE_FORM";
export const TOGGLE_VIEW = "TOGGLE_VIEW";
export const TOGGLE_MODAL = "TOGGLE_MODAL";

// Misc: Auth
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
